server:
  port: 8082
# \u6570\u636E\u6E90\u914D\u7F6E
spring:
  redis:
    database: 0
    host: 172.16.127.11
    port: 6379
    password:      # \u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
    timeout: 6000ms  # \u8FDE\u63A5\u8D85\u65F6\u65F6\u957F\uFF08\u6BEB\u79D2\uFF09
    lettuce:
      pool:
        max-active: 1000  # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-wait: -1ms      # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-idle: 10      # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 5       # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: jiava123
mybatis:
  type-aliases-package: com.microvideo.springboot_resource_analysis.mapper